
[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "hp_math"
description = "Simple script for high performance mathematical visualizations."
readme = "README.md"
version = "0.0.1"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
